# Generated by Django 4.1.5 on 2023-01-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('rfc', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='GestionMobiliaria',
            fields=[
                ('id_gestionm', models.SmallAutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=80)),
                ('reposicion', models.SmallIntegerField()),
                ('precio_renta', models.SmallIntegerField()),
                ('cantidad', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenusComida',
            fields=[
                ('id_menusc', models.SmallAutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=80)),
                ('descripcion', models.TextField(max_length=600)),
                ('precio_persona', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.SmallAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('precio_evento', models.SmallIntegerField()),
                ('cantidad', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalVehiculos',
            fields=[
                ('id_personalv', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('edad', models.SmallIntegerField()),
                ('estatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculos', models.SmallAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=80)),
                ('estatus', models.BooleanField()),
                ('combustible', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.SmallAutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.SmallIntegerField()),
                ('subtotal', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('total', models.IntegerField()),
                ('a_cuenta', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAlquiladora.clientes')),
                ('menusc', models.ManyToManyField(to='AppAlquiladora.menuscomida')),
                ('mobiliario', models.ManyToManyField(to='AppAlquiladora.gestionmobiliaria')),
                ('personal', models.ManyToManyField(to='AppAlquiladora.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.SmallAutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('a_cuenta', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField()),
                ('estatus', models.SmallIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAlquiladora.clientes')),
                ('menusc', models.ManyToManyField(to='AppAlquiladora.menuscomida')),
                ('mobiliario', models.ManyToManyField(to='AppAlquiladora.gestionmobiliaria')),
                ('personal', models.ManyToManyField(to='AppAlquiladora.personal')),
            ],
        ),
    ]
